// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: my_speedo

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_img_bg;
extern lv_obj_t * ui_img_needle;
extern lv_obj_t * ui_Arc_rpm;
extern lv_obj_t * ui_lbl_1;
extern lv_obj_t * ui_lbl_2;
extern lv_obj_t * ui_lbl_rpm_value;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_img_bg;
extern lv_obj_t * uic_img_needle;
extern lv_obj_t * uic_Arc_rpm;
extern lv_obj_t * uic_lbl_1;
extern lv_obj_t * uic_lbl_2;
extern lv_obj_t * uic_lbl_rpm_value;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

