// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: my_speedo

#include "../ui.h"

lv_obj_t * uic_lbl_rpm_value;
lv_obj_t * uic_lbl_2;
lv_obj_t * uic_lbl_1;
lv_obj_t * uic_Arc_rpm;
lv_obj_t * uic_img_needle;
lv_obj_t * uic_img_bg;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_img_bg = NULL;
lv_obj_t * ui_img_needle = NULL;
lv_obj_t * ui_Arc_rpm = NULL;
lv_obj_t * ui_lbl_1 = NULL;
lv_obj_t * ui_lbl_2 = NULL;
lv_obj_t * ui_lbl_rpm_value = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_bg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_img_bg, &ui_img_1834619086);
    lv_obj_set_width(ui_img_bg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_bg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_needle = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_img_needle, &ui_img_951008474);
    lv_obj_set_width(ui_img_needle, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_img_needle, LV_SIZE_CONTENT);    /// 89
    lv_obj_set_x(ui_img_needle, 108);
    lv_obj_set_y(ui_img_needle, 151);
    lv_obj_add_flag(ui_img_needle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_needle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_img_needle, 10, -29);

    ui_Arc_rpm = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc_rpm, 211);
    lv_obj_set_height(ui_Arc_rpm, 211);
    lv_obj_set_align(ui_Arc_rpm, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc_rpm, 0);
    lv_arc_set_bg_angles(ui_Arc_rpm, 90, 0);
    lv_obj_set_style_arc_color(ui_Arc_rpm, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_rpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc_rpm, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc_rpm, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_rpm, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc_rpm, 52, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc_rpm, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc_rpm, &ui_img_1979378346, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc_rpm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc_rpm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbl_1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lbl_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_1, 4);
    lv_obj_set_y(ui_lbl_1, -57);
    lv_obj_set_align(ui_lbl_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_1, "x1000rpm");
    lv_obj_set_style_text_color(ui_lbl_1, lv_color_hex(0xC2030F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_1, &ui_font_t13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lbl_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_2, 54);
    lv_obj_set_y(ui_lbl_2, 73);
    lv_obj_set_align(ui_lbl_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_2, "kmph");
    lv_obj_set_style_text_color(ui_lbl_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_2, &ui_font_t20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_rpm_value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lbl_rpm_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_rpm_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_rpm_value, 59);
    lv_obj_set_y(ui_lbl_rpm_value, 44);
    lv_obj_set_align(ui_lbl_rpm_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_rpm_value, "---");
    lv_obj_set_style_text_color(ui_lbl_rpm_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_rpm_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbl_rpm_value, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_rpm_value, &ui_font_t40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_images_car_icon_240_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 80);
    lv_obj_set_y(ui_Image4, 9);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_images_temperature_png);
    lv_obj_set_width(ui_Image5, 32);
    lv_obj_set_height(ui_Image5, 32);
    lv_obj_set_x(ui_Image5, 96);
    lv_obj_set_y(ui_Image5, -14);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 88);
    lv_obj_set_y(ui_Label4, 11);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "60°C");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x1E90FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_t13, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_img_bg = ui_img_bg;
    uic_img_needle = ui_img_needle;
    uic_Arc_rpm = ui_Arc_rpm;
    uic_lbl_1 = ui_lbl_1;
    uic_lbl_2 = ui_lbl_2;
    uic_lbl_rpm_value = ui_lbl_rpm_value;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_img_bg = NULL;
    ui_img_bg = NULL;
    uic_img_needle = NULL;
    ui_img_needle = NULL;
    uic_Arc_rpm = NULL;
    ui_Arc_rpm = NULL;
    uic_lbl_1 = NULL;
    ui_lbl_1 = NULL;
    uic_lbl_2 = NULL;
    ui_lbl_2 = NULL;
    uic_lbl_rpm_value = NULL;
    ui_lbl_rpm_value = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Label4 = NULL;

}
