// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: my_speedo

#ifndef _MY_SPEEDO_UI_H
#define _MY_SPEEDO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * needle_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1834619086);    // assets/images/gauge-bg_240.png
LV_IMG_DECLARE(ui_img_951008474);    // assets/images/gauge-needle_240.png
LV_IMG_DECLARE(ui_img_1979378346);    // assets/images/gauge-indicator_240.png
LV_IMG_DECLARE(ui_img_images_car_icon_240_png);    // assets/images/car_icon_240.png
LV_IMG_DECLARE(ui_img_images_temperature_png);    // assets/images/temperature.png

// FONTS
LV_FONT_DECLARE(ui_font_t20);
LV_FONT_DECLARE(ui_font_t25);
LV_FONT_DECLARE(ui_font_t13);
LV_FONT_DECLARE(ui_font_t40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
